### ISSUE TITLE
[Refactor 💡] 전반적인 프로젝트 재정비

### ISSUE THREAD

**Issue by yu-heejin** [WAGGLE-TEAM/WAGGLE_BACKEND#47]
## Description ✏️
* 프로젝트 재정비를 진행합니다.

## TODO
- [ ] 폴더 구조 변경
- [x] build.gradle 변경
- [ ] chatting API 전반적인 수정
- [ ] 사용하지 않는 코드 삭제
- [ ] Java 17 + Spring Boot 3 마이그레이션
